#!/hint/bash

FTP_BASE="/srv/ftp"
ARCHIVE_BASE="/srv/archive"
ARCHIVE_INDEX_URL="https://archive.archlinux.org/packages/.all/index.0.xz"
ARCHIVEUSER='archive'
PKGREPOS=()
DEBUGREPOS=()
PKGPOOL=''
SRCPOOL=''
DEBUGPKGPOOL=''
UNSTABLE_REPOS=()
STAGING_REPOS=()
TESTING_REPOS=()
STABLE_REPOS=()
STABILITY_LAYERS=(stable testing staging unstable)
declare -A ACL=()

CLEANUP_DESTDIR="/var/tmp"
CLEANUP_DRYRUN=false
# Time in days to keep moved packages
CLEANUP_KEEP=30

SOURCE_CLEANUP_DESTDIR="/var/tmp"
SOURCE_CLEANUP_DRYRUN=false
# Time in days to keep moved sourcepackages
SOURCE_CLEANUP_KEEP=14

LOCK_DIR="/var/tmp"

STAGING="$HOME/staging"
export TMPDIR="/var/tmp"
ARCHES=(x86_64)
DBEXT=".db.tar.gz"
FILESEXT=".files.tar.gz"
SRCEXT=".src.tar.gz"

# bash glob listing allowed extensions. Note that db-functions turns on extglob.
PKGEXTS=".pkg.tar.@(gz|bz2|xz|zst|lrz|lzo|Z|lz4|lz)"
PKGEXT_DEFAULT=".pkg.tar.zst"

# Allowed licenses: get sourceballs only for licenses in this array
ALLOWED_LICENSES=('GPL' 'GPL1' 'GPL2' 'GPL3' 'LGPL' 'LGPL1' 'LGPL2' 'LGPL2.1' 'LGPL3' 'AGPL3')

# Where to send error emails, and who they are from
LIST="arch-dev-public@lists.archlinux.org"
#LIST="aaronmgriffin@gmail.com"
FROM="repomaint@archlinux.org"

# curated PATH to sanitize executables in a portable way
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export PATH

AUTHORS=/etc/dbscripts/authors.conf
PACKAGER_DOMAIN=archlinux.org

# Override default config with config.local
LOCAL_CONFIG=${DBSCRIPTS_CONFIG:-"$(dirname "${BASH_SOURCE[0]}")/config.local"}
[[ -f "${LOCAL_CONFIG}" ]] && . "${LOCAL_CONFIG}"

umask 002
