#!/bin/bash

. "$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")/config"

if (( $# != 1 )); then
	echo "usage: %s <pkgfile>" "${0##*/}"
	exit 1
fi

if [[ -n ${ARCHIVEUSER} && ${USER} != ${ARCHIVEUSER} ]]; then
	exec sudo -u "${ARCHIVEUSER}" "${BASH_SOURCE[0]}" "${@}"
fi

pkgfile=${1##*/}
pkgname=${pkgfile%-*-*-*}
archive_dir="${ARCHIVE_BASE}/packages/${pkgname:0:1}/${pkgname}"

if [[ ! -f ${archive_dir}/${pkgfile} ]]; then
	mkdir -p "${archive_dir}"
	cp -p "${1}" "${archive_dir}/.${pkgfile}"
	cp -p "${1}.sig" "${archive_dir}/.${pkgfile}.sig"

	mv "${archive_dir}/"{.,}"${pkgfile}"
	mv "${archive_dir}/"{.,}"${pkgfile}.sig"
fi
