#!/bin/bash

. "$(dirname "$(readlink -e "$0")")/config"
. "$(dirname "$(readlink -e "$0")")/db-functions"

set -eo pipefail
shopt -s nullglob

colorize

usage() {
	cat <<- _EOF_
	Usage: ${BASH_SOURCE[0]##*/} [OPTIONS] REPO PKGNAME...

	OPTIONS:
	    -a, --arch ARCH    Remove packages exclusively from ARCH instead of everywhere
	    -h, --help         Show this help text
_EOF_
}

arch=any

# option checking
while (( $# )); do
	case $1 in
		-h|--help)
			usage
			exit 0
			;;
		-a|--arch)
			(( $# <= 1 )) && die "missing argument for %s" "$1"
			arch=$2
			shift 2
			if [[ "${arch}" != any ]] && ! in_array "${arch}" "${ARCHES[@]}"; then
				die "invalid architecture: %s" "${arch}"
			fi
			;;
		-*)
			die "invalid argument: %s" "$1"
			;;
		*)
			break
			;;
	esac
done

if (( $# < 2 )); then
	usage
	exit 1
fi

if [[ $arch = any ]]; then
	tarches=("${ARCHES[@]}")
	vcsarches=("${ARCHES[@]}")
	vcsarches+=(any)
else
	tarches=("$arch")
	vcsarches=("$arch")
fi

repo="$1"
pkgnames=("${@:2}")
# TODO: Temporary compatibility mode for more fluent rollout
if [[ "$2" == any ]]; then
	pkgnames=("${@:3}")
fi

# filter out duplicates
mapfile -t pkgnames < <(printf '%s\n' "${pkgnames[@]}" | sort --unique)

if ! in_array "${repo}" "${PKGREPOS[@]}"; then
	die "Unknown target repository %s" "${repo}"
fi
if ! check_repo_permission "$repo"; then
	die "You don't have permission to remove packages from %s" "$repo"
fi
if ! check_author; then
	die "You don't have a matching author mapping"
fi

# lock repos
for tarch in "${tarches[@]}"; do
	repo_lock "$repo" "$tarch"
done

declare -A remove_pkgnames
declare -A remove_pkgs
declare -A remove_debug_pkgs
declare -A handled_pkgnames

for pkgname in "${pkgnames[@]}"; do
	for tarch in "${vcsarches[@]}"; do
		vcsrepo="$repo-$tarch"

		# try to get pkgname metadata from state repo
		if ! _pkgver=$(pkgver_from_state_repo "${pkgname}" "${vcsrepo}"); then
			continue
		fi

		array_append remove_pkgnames "${vcsrepo}" "${pkgname}"
		handled_pkgnames["${pkgname}"]=1

		# loop through all arches for any packages
		remove_arches=("${tarch}")
		if [[ ${tarch} == any ]]; then
			remove_arches=("${tarches[@]}")
		fi

		# remove pkgnames
		for remove_arch in "${remove_arches[@]}"; do
			msg "Removing %s from %s [%s]..." "${pkgname}" "${repo}" "${remove_arch}"
			array_append remove_pkgs "${remove_arch}" "${pkgnames[*]}"
		done

		# check to remove debug packages
		for remove_arch in any "${remove_arches[@]}"; do
			if is_globfile "${FTP_BASE}/${repo}-debug/os/${remove_arch}/${pkgname}-debug"-*-*-*.pkg.tar*; then
				msg "Found debug package. Removing %s from %s [%s]..." "${pkgname}-debug" "${repo}-debug" "${remove_arch}"
				array_append remove_debug_pkgs "${remove_arch}" "${pkgname}-debug"
			fi
		done
	done
done

# check for unhandled arguments before executing
for pkgname in "${pkgnames[@]}"; do
	if [[ ! "${handled_pkgnames["${pkgname}"]+exists}" ]]; then
		die "Package not found in %s: %s" "${repo}" "${pkgname}"
	fi
done

# remove binary repo packages
for key in "${!remove_pkgs[@]}"; do
	tarch=${key}
	read -ra pkgs <<< "${remove_pkgs[$key]}"
	arch_repo_modify remove "${repo}" "${tarch}" "${pkgs[@]}"
done

# remove binary repo debug packages
for key in "${!remove_debug_pkgs[@]}"; do
	tarch=${key}
	read -ra pkgs <<< "${remove_debug_pkgs[$key]}"
	arch_repo_modify remove "${repo}-debug" "${tarch}" "${pkgs[@]}"
done

# remove state repo entry
for key in "${!remove_pkgnames[@]}"; do
	vcsrepo=${key}
	read -ra pkgs <<< "${remove_pkgnames[$key]}"
	for pkgname in "${pkgs[@]}"; do
		vcs_remove_package "${pkgname}" "${vcsrepo}"
	done
done

# Remove all the locks we created
for tarch in "${tarches[@]}"; do
	repo_unlock "$repo" "$tarch"
done
